version: '2'
services:
 proxy:
  build: ./
  networks:
   - website1
   - website2
  ports:
   - 80:80
   - 443:443

networks:
 website1:
  external:
   name: website1_default
 website2:
  external:
   name: website2_default
